name: PR size label
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: "50"
          s_max_size: "150"
          m_max_size: "300"
          l_max_size: "600"
          fail_if_xl: "false"
